version: 2
updates:
  # Fetch and update latest `npm` packages
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
      day: 'friday'
      time: '08:30'
      timezone: 'Asia/Shanghai'
    versioning-strategy: auto
    open-pull-requests-limit: 0
    reviewers:
      - wusongliang
    assignees:
      - wusongliang
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
  # Fetch and update latest `github-actions` pkgs
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: weekly
      day: 'friday'
      time: '08:30'
      timezone: 'Asia/Shanghai'
    open-pull-requests-limit: 0
    reviewers:
      - wusongliang
    assignees:
      - wusongliang
    commit-message:
      prefix: ci
      include: scope
